name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/slack-sensei:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into VM and update container
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/slack-sensei:latest
          docker stop slack-sensei || true
          docker rm slack-sensei || true
          docker run -d --name slack-sensei -p 5000:5000 \
            -e SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }} \
            -e SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }} \
            -e GROQ_API_TOKEN=${{ secrets.GROQ_API_TOKEN }} \
            -e FLASK_DEBUG=${{ secrets.FLASK_DEBUG }} \
            ${{ secrets.DOCKER_USERNAME }}/slack-sensei:latest
